### PR TITLE
Added Status 510

### PR DESCRIPTION
**Pull request by strangeloveBsc**
Reordered the columns, too. 
Now the third one is the shortest.

### CODE REVIEW

**Comment by rogeriopvl** [comment]
@strangeloveBsc You missed the `index.html`. Right now, changes have to be made to both `index.html` and `catala/index.html`.

**Comment by strangeloveBsc** [comment]
Noted. Will take care of it asap, thanks.

**Comment by strangeloveBsc** [comment]
@rogeriopvl please recheck and (hopefully) greenlight. Thanks ;3

**Comment by rogeriopvl** [comment]
It's live! https://http.cat/510

thanks! 🙏

**Comment by rogeriopvl** [comment]
@all-contributors add @strangeloveBsc for content and design

**Pull request merged**
